# Generated by Django 4.2.6 on 2023-10-30 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_alter_course_image'),
        ('lesson', '0005_remove_lesson_course_lesson_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(max_length=100, verbose_name='дата оплаты')),
                ('count', models.CharField(max_length=100, verbose_name='сумма оплаты')),
                ('payment_type_cash', models.BooleanField(default=False, verbose_name='оплата наличными')),
                ('payment_type_credit_card', models.BooleanField(default=False, verbose_name='оплата картой')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
                'ordering': ('payment_date',),
            },
        ),
    ]
