# Generated by Django 4.2.6 on 2023-11-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type_cash',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='оплата наличными'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type_credit_card',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='оплата картой'),
        ),
    ]
