# Generated by Django 4.2.6 on 2023-11-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'memeber'), ('moderator', 'moderator')], default='member', max_length=9),
        ),
    ]
