# Generated by Django 4.2.6 on 2023-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='курс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='превью (картинка)')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ('name',),
            },
        ),
    ]
