# Generated by Django 4.2.6 on 2023-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='урок')),
                ('description', models.TextField(max_length=300, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='превью (картинка)')),
                ('link', models.URLField(blank=True, max_length=300, null=True, verbose_name='ссылка на видео')),
                ('сourse', models.ManyToManyField(to='course.course')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ('name',),
            },
        ),
    ]
