# Generated by Django 4.2.6 on 2023-10-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_lesson_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='сourse',
            new_name='course',
        ),
    ]
